.github/pull_request_template.md, .github/workflows/post-merge-dynamo-to-build.yml, .github/workflows/post-merge-dynamo-to-dev.yml, .github/workflows/post-merge-kms-build.yml, .github/workflows/post-merge-kms-dev.yml
Adding GHA workflows for KMS and DynamoDB deployments to DEV and BUILD.
These workflows are required to deploy stacks that will be created in:
https://govukverify.atlassian.net/browse/F2F-72 
and 
https://govukverify.atlassian.net/browse/F2F-96
Also adding pull request template.
=> PLAT-790: GHA workflow DDB, KMS

infra-l2-outbound-proxy/src/tests/infra/infra.test.ts, infra-l2-outbound-proxy/template.yaml
Add the `/yoti` and Yoti proxy integration to the outbound proxy APIGW
Integrate the Yoti service following the same pattern as with PO
- [F2F-347](https://govukverify.atlassian.net/browse/F2F-347)
[F2F-347]: https://govukverify.atlassian.net/browse/F2F-347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-347] Add Yoti integration to outbound proxy

deploy/template.yaml, src/README.md, src/tests/infra/template.test.ts
Adds custom domain DNS record, APIGW custom domain definition and base path mapping for the backend API Gateway, and associated infra tests
Custom domains need to be defined alongside the APIGW resource definition in the same template, so they are created and destroyed together
- [F2F-471](https://govukverify.atlassian.net/browse/F2F-471)
[F2F-471]: https://govukverify.atlassian.net/browse/F2F-471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-471] Add custom domain definition and mapping for BE APIGW

f2f-ipv-stub/template.yaml
Adding IPV Stub subdomain and api mapping 
To enable other components like F2F /session to call its well-known endpoint to fetch the public key
- [F2F-501](https://govukverify.atlassian.net/browse/F2F-501)
[F2F-501]: https://govukverify.atlassian.net/browse/F2F-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-501: Adding IPV Stub subdomain and api mapping

deploy/template.yaml, src/services/DocumentSelectionRequestProcessor.ts, src/tests/unit/services/DocumentSelectionRequestProcessor.test.ts, src/utils/TxmaEvent.ts
The event F2F_YOTI_START is emitted from F2F BE to the TxMA SQS queue using sqs:SendMessage
This is done after the Yoti session (authSession) is created
=> F2F | BE | Emit F2F_YOTI_START event

deploy/template.yaml
Add PermissionsBoundary to `YotiCallbackQueueRole` as its required by pipelines on higher environments in order to create a new role
=> Adding permissions boundary for YotiQueueRole

deploy/template.yaml
Update Yoti URL for dev to point to the deployed Yoti Stub
In dev we no longer want to be having direct integration to Yoti production 
https://govukverify.atlassian.net/browse/F2F-675
=> F2F | BE | Update Dev stack to use YotiStub

deploy/template.yaml, src/tests/infra/template.test.ts
Added a MethodSettings block to the Serverless::Api definition
Enables the APIGW execution logs; and ensures detailed data trace (request/response) logging is only enabled in environments not handling PII.
- [F2F-718](https://govukverify.atlassian.net/browse/F2F-718)
[F2F-718]: https://govukverify.atlassian.net/browse/F2F-718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-718 Add MethodSettings to REST APIGW definition

deploy/samconfig.toml, deploy/template.yaml, infra-l2-dynamo/template.yaml, src/YotiCallbackHandler.ts, src/models/YotiPayloads.ts, src/package.json, src/services/GenerateVerifiableCredential.ts, src/services/VerifiableCredentialService.ts, src/services/YotiCallbackProcessor.ts, src/services/YotiService.ts, src/tests/api/Yoti.test.ts, src/tests/unit/YotiCallbackHandler.test.ts, src/tests/unit/data/callback-events.ts, src/tests/unit/services/DocumentSelectionRequestProcessor.test.ts, src/tests/unit/services/GenerateVerifiableCredential.test.ts, src/tests/unit/services/VerifiableCredentialService.test.ts, src/tests/unit/services/YotiCallbackProcessor.test.ts, src/tests/unit/services/YotiService.test.ts, src/utils/IVeriCredential.ts, src/utils/PersonIdentityUtils.ts, src/utils/YotiPayloadEnums.ts
Parses the returned completed session from YOTI and generates a fully formed VC object containing the necessary evidence objects and scores to send back to IPV Core
https://govukverify.atlassian.net/browse/F2F-502
**Example VC**
=> [F2F-502] Convert Yoti Response into VC Format

yoti-stub/src/data/getSessions/aiPass.ts
Updates the response for 0103 scenario (UK Passport Success - Chip NOT readable & Face Match NOT automated) by adding `manual_face_match `
It wasn't there
- [F2F-761](https://govukverify.atlassian.net/browse/F2F-761)
[F2F-761]: https://govukverify.atlassian.net/browse/F2F-761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-761] Adds manual_face_match to response for GET sessions/0103 in Yoti Mock

yoti-stub/template.yaml
Removed the api url in the MockYotiApiGatewayCustomDomain resource which was added in error
Was causing pipeline failures
- [F2F-710](https://govukverify.atlassian.net/browse/F2F-710)
[F2F-710]: https://govukverify.atlassian.net/browse/F2F-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-710: Amended Yoti Domain Name Resource

src/services/YotiCallbackProcessor.ts, src/tests/unit/services/F2fService.test.ts, src/tests/unit/services/YotiCallbackProcessor.test.ts, src/utils/IPVCoreEvent.ts
Modifying response to contain JWT in a list instead of string as per ADR: https://github.com/alphagov/digital-identity-architecture/blob/main/adr/0058-cri-ipv-async-result-comms.md
IPC Core lambda unable to parse the SQS message
- [F2F-767](https://govukverify.atlassian.net/browse/F2F-767)
[F2F-767]: https://govukverify.atlassian.net/browse/F2F-767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-767] Modifying response to add JWT as a list instead of string

src/tests/data/integrationUnHappyPathPayload.json, yoti-stub/src/data/getMediaContent/espPassportResponse.ts, yoti-stub/src/services/YotiRequestProcessor.ts, yoti-stub/src/utils/Constants.ts
Updating the yoti mock to cover an unhappy path for a Non-UK passport
- [F2F-769](https://govukverify.atlassian.net/browse/F2F-769)
[F2F-769]: https://govukverify.atlassian.net/browse/F2F-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-769]-Update the mock to cover an unhappy path for a Non-UK passport

yoti-stub/src/services/YotiRequestProcessor.ts
Modified response for  GET /sessions/{sessionId}/instructions/pdf in Yoti stub to return a PDF file for positive scenario
To fix defect as was returning a text file with payload errors
- [F2F-859](https://govukverify.atlassian.net/browse/F2F-859)
**Testing**
https://github.com/alphagov/di-ipv-cri-f2f-api/assets/26764987/333231ba-3868-46e1-9b43-48754fc17999
[F2F-859]: https://govukverify.atlassian.net/browse/F2F-859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-859]: Returning PDF file for Yoti stub GET /sessions/{sessionId}/instructions/pdf

src/jest.setup.ts, src/tests/unit/services/SendEmailService.test.ts
Added unit-tests to test GovNotify's retry logic when 500/429 errors are received.
To be able to verify that the re-try logic in GovNotify works as expected.
=> [F2F-490] Adding unit-tests to test govNotify retry logic

deploy/template.yaml
- Disabled the TxMA and IPV core services SQS message subscriptions.
- This is done temporarily for Production testing. 
- [F2F-838](https://govukverify.atlassian.net/browse/F2F-838)
[F2F-838]: https://govukverify.atlassian.net/browse/F2F-838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-838: Production Testing | Disable permissions to SQS receive functions

yoti-stub/src/MockYotiSessionHandler.ts, yoti-stub/src/services/YotiRequestProcessor.ts
Logs out the /createSession payload in Yoti Mock to verify changes in documentSelection are as expected
https://govukverify.atlassian.net/browse/F2F-910
**/createSession**
**PUT Instructions**
=> F2F-910 Enhance logging in Yoti Mock

src/services/YotiService.ts, src/tests/unit/services/DocumentSelectionRequestProcessor.test.ts, src/tests/unit/services/YotiCallbackProcessor.test.ts, src/tests/unit/services/YotiService.test.ts, src/utils/PersonIdentityUtils.ts, src/utils/YotiPayloadEnums.ts, yoti-stub/src/data/createSession.ts, yoti-stub/src/data/getSessions/aiPass.ts, yoti-stub/src/data/getSessions/responses.ts, yoti-stub/src/models/YotiSessionRequest.ts, yoti-stub/yoti-spec.yaml
- Adds any middle names the user supplies in FE when making call to create Session and PUT Instructions (Generate PDF) in Yoti
- Change the scheme from UK_DBS to UK_GDS to allow for postmaster to accept passports expired within the past 18 months
- Adds building number to address_line1 for applicant profile
- null checks on buldingName so empty strings aren't added in address_line1
https://govukverify.atlassian.net/browse/F2F-908
=> F2F-908 Resolving misalignment with Address and name fields in request to Yoti

src/models/YotiPayloads.ts, src/services/YotiService.ts, src/tests/unit/services/YotiService.test.ts
As part of https://github.com/alphagov/di-ipv-cri-f2f-api/pull/150 we reverted changes to accept PO name from FE. Adding this change back in but making it conditional so the BE is not dependant on the FE sending this value.
If present the PO name will be sent to YOTI else a Hardcoded value will be sent
https://govukverify.atlassian.net/browse/F2F-909
**Without Name**
**WIth Name**
=> [F2F-909] Adding backward compatible PO Name to /documentSelection

src/tests/api/DocumentSelectionNegativePath.test.ts
Reverting validation message change on expired auth header
The validation message was incorrectly updated yesterday as no header was provided in the request.  
- [F2F-966](https://govukverify.atlassian.net/browse/F2F-966)
[F2F-966]: https://govukverify.atlassian.net/browse/F2F-966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> reverting validation message change on expired auth header

deploy/template.yaml, src/tests/infra/template.test.ts
Changed F2FBackendURL output which is used by run-tests.sh script.
F2FBackendURL in build had incorrect format.
- [F2F-977](https://govukverify.atlassian.net/browse/F2F-977)
Test Results
[F2F-977]: https://govukverify.atlassian.net/browse/F2F-977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed the backend URL in template F2FBackendURL

src/tests/api/AbortApi.test.ts
Update the tests so they generate a session dynamically then attempt to abort. This will ensure these tests can run in any env.
Abort tests now generate a session instead of using a hard coded one. 
An issue has been identified with the /abort backend tests where the hardcoded session ID exists in dev but not build. 
- [F2F-983](https://govukverify.atlassian.net/browse/F2F-983)
[F2F-983]: https://govukverify.atlassian.net/browse/F2F-983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-983]: https://govukverify.atlassian.net/browse/F2F-983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> abort test fixed in build

f2f-ipv-stub/src/handlers/startF2fCheck.ts
The response payload of the call to the sub `/start` endpoint now includes the randomly generated `sub` and `state` in the response payload.
So that they can be used in the test harness in later calls to find outputs generated from this request
- [F2F-1045](https://govukverify.atlassian.net/browse/F2F-1045)
[F2F-1045]: https://govukverify.atlassian.net/browse/F2F-1045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-1045 Update stub to return `sub` and `state`

README.md, deploy/template.yaml
Set reserved concurrencies for all lambdas which are deployed in all non-DEV environments. These are required in BUILD since this is the environment used in performance testing. A parameter has been added to allow them to be set when manually deploying in DEV should this be needed, but this must not be default.
Per requirements on ticket
- [F2F-780](https://govukverify.atlassian.net/browse/F2F-780)
[F2F-780]: https://govukverify.atlassian.net/browse/F2F-780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-780: Set reserved concurrencies for Lambdas in non-DEV environments

src/services/YotiCallbackProcessor.ts, src/tests/unit/data/txmaEvent.ts, src/tests/unit/services/YotiCallbackProcessor.test.ts
Updated the name value sent in the F2F_CRI_VC_ISSUED event 
Changes requested
- [F2F-1107](https://govukverify.atlassian.net/browse/F2F-1107)
- Relies on changes from F2F-1000
[F2F-1107]: https://govukverify.atlassian.net/browse/F2F-1107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-1107] Updates name in TxMA F2F_CRI_VC_ISSUED event

src/services/SessionRequestProcessor.ts
Fixing the way we fetch the ipAddress for TXMA events.
Bug during regression testing
- [F2F-1113](https://govukverify.atlassian.net/browse/F2F-1113)
[F2F-1113]: https://govukverify.atlassian.net/browse/F2F-1113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-1113] Fixing the way we fetch the ipAddress for TXMA events.

deploy/template.yaml
- SessionConfig function was pointing to wrong log group and now modified to point to the right log group
- [F2F-1114](https://govukverify.atlassian.net/browse/F2F-1114)
Test evidence in ticket above.
[F2F-1114]: https://govukverify.atlassian.net/browse/F2F-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-1114: Lambdas Sending Logs to the Wrong Log Groups

infra-l2-dynamo/template.yaml, test-harness/test-harness-spec.yaml
Removing the old authorizationCode-index index which is unused and its references.
We created a new index authCode-index for F2F-1081 which is deployed now in prod and working as expected. Removing the unused index as part of this PR.
- [F2F-1099](https://govukverify.atlassian.net/browse/F2F-1099)
[F2F-1099]: https://govukverify.atlassian.net/browse/F2F-1099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-1099] Removing authorizationCode-index and its references

deploy/template.yaml
Modified the concurrency80Alarms to Critical as per the requirements to send notifications to 2nd line support.
- [F2F-1139](https://govukverify.atlassian.net/browse/F2F-1139)
[F2F-1139]: https://govukverify.atlassian.net/browse/F2F-1139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-1139: Change concurrency80Alarms to critical alarms

infra-l2-dynamo/template.yaml, src/utils/Constants.ts, test-harness/test-harness-spec.yaml
Pulls out yotiSessionId index change
Pipeline is broken as we are only able to make one index change at a time, but https://github.com/alphagov/di-ipv-cri-f2f-api/pull/183 had two
yotiSessionId-updated-index no longer present
Callback API tests passing
- [F2F-672](https://govukverify.atlassian.net/browse/F2F-672)
[F2F-672]: https://govukverify.atlassian.net/browse/F2F-672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-672] Pulls out yotiSessionId index change

src/services/GenerateVerifiableCredential.ts
Adding logs to GenerateVerifiableCredential to expose more info about the Yoti completed session response
https://govukverify.atlassian.net/browse/F2F-1163
=> [F2F-1163] - Adding logs to GenerateVerifiableCredential

src/tests/api/CallbackApi.test.ts, src/tests/data/F2F_CRI_VC_ISSUED_00_SCHEMA.json, src/tests/data/F2F_CRI_VC_ISSUED_01_SCHEMA .json, src/tests/data/F2F_CRI_VC_ISSUED_02_SCHEMA.json, src/tests/data/F2F_CRI_VC_ISSUED_03_SCHEMA.json, src/tests/data/F2F_CRI_VC_ISSUED_04_SCHEMA.json, src/tests/data/F2F_CRI_VC_ISSUED_05_SCHEMA.json, src/tests/data/F2F_YOTI_START_00_SCHEMA.json, src/tests/data/F2F_YOTI_START_01_SCHEMA.json, src/tests/data/F2F_YOTI_START_02_SCHEMA.json, src/tests/data/F2F_YOTI_START_03_SCHEMA.json, src/tests/data/F2F_YOTI_START_04_SCHEMA.json, src/tests/data/F2F_YOTI_START_05_SCHEMA.json, src/tests/utils/ApiTestSteps.ts
Additional documentTypes added to TxMA validation tests
Additional coverage in BE pipeline regression tests
- [F2F-1173](https://govukverify.atlassian.net/browse/F2F-1173)
=> Additional documentTypes in TxMA Validation

src/models/YotiPayloads.ts, src/services/YotiCallbackProcessor.ts, src/tests/api/CallbackApi.test.ts, src/tests/unit/services/YotiCallbackProcessor.test.ts, yoti-stub/src/services/YotiRequestProcessor.ts
Throw error where there is no document_fields, enhance logging so we can see why this happened
Mock updated with data from https://drive.google.com/drive/folders/1iEsLz1qOIDdcyWE-asx4BbfOD3Sv3PMf
To handle production error and help us to debug it in the future
- [F2F-1167](https://govukverify.atlassian.net/browse/F2F-1167)
[F2F-1167]: https://govukverify.atlassian.net/browse/F2F-1167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-1167] enhance logging and throw error where there is no document_fields

infra-l2-dynamo/template.yaml
Removing the Unused authCode-index
Tech debt
- [KIWI-1138](https://govukverify.atlassian.net/browse/KIWI-1138)
Evidence:
Before indexes: 
After index list:
[KIWI-1138]: https://govukverify.atlassian.net/browse/KIWI-1138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1138]Remove Unused authCode-index

src/services/ThankYouEmailProcessor.ts, src/tests/unit/services/ThankYouEmailProcessor.test.ts
Use` hourCycle` instead of `hour12` as it seems that en-GB has a default hour cycle of 11/23 meaning that it considers 11 the end of a cycle rather than 12 - see docs https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#options
So that we shown 12pm rather than 0pm 
- [KIWI-1254](https://govukverify.atlassian.net/browse/KIWI-1254)
Before 
After 
[KIWI-1254]: https://govukverify.atlassian.net/browse/KIWI-1254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1254] fix hour cycle

deploy/template.yaml, src/services/F2fService.ts, src/services/ReminderEmailProcessor.ts, src/tests/unit/services/F2fService.test.ts, src/tests/unit/services/ReminderEmailProcessor.test.ts
Update the DB Query for ReminderEmail to include all states the F2F Session could be from the point where the user has started a F2F Journey but has not aborted their journey and have not yet visited the PO
=> [KIWI-1243] - Include all necessary states for ReminderEmail

deploy/template.yaml
Adds GOVUKNOTIFYREMINDERTEMPLATEID env var to integration env
Because it was missing and breaking the integration pipeline
- [F2F-1275](https://govukverify.atlassian.net/browse/F2F-1275)
=> [KIWI-1275] Adds GOVUKNOTIFYREMINDERTEMPLATEID env var to integration env

deploy/template.yaml, infra-l2-dynamo/template.yaml, src/jest.setup.ts, src/models/DynamicReminderEmail.ts, src/models/enums/DocumentTypes.ts, src/services/DocumentSelectionRequestProcessor.ts, src/services/EnvironmentVariables.ts, src/services/F2fService.ts, src/services/ReminderEmailProcessor.ts, src/services/SendEmailProcessor.ts, src/services/SendEmailService.ts, src/tests/unit/data/sqs-events.ts, src/tests/unit/services/DocumentSelectionRequestProcessor.test.ts, src/tests/unit/services/F2fService.test.ts, src/tests/unit/services/ReminderEmailProcessor.test.ts, src/tests/unit/services/SendEmailProcessor.test.ts, src/tests/unit/services/SendEmailService.test.ts, src/utils/Constants.ts, src/utils/GovNotifyEvent.ts
- Saves users selected Document Type to the Session Table
- Adds users selected Document Type, FirstName and LastName to the Reminder Email Template
- Conditionally sends either the static or dynamic email template based on available data
https://govukverify.atlassian.net/browse/KIWI-1227
=> [KIWI-1227] - Send Dynamic Reminder Emails

Dockerfile
Replaces deprecated script in Dockerfile
To save time in our local runs
- [F2F-1299](https://govukverify.atlassian.net/browse/F2F-1299)
No issues when running `run-tests-locally`
=> [KIWI-1299] Replaces deprecated script in Dockerfile

src/tests/api/CallbackApi.test.ts, src/tests/data/vcValidationData.json, src/tests/utils/ApiTestSteps.ts
QA Updates to test KIWI-1164
Test updates to add Contra Indicator score + reason to F2F_CRI_VC_ISSUED TxMA Event
- [KIWI-1164](https://govukverify.atlassian.net/browse/KIWI-1164)
[KIWI-1164]: https://govukverify.atlassian.net/browse/KIWI-1164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1164-QA

infra-l2-outbound-proxy/src/tests/infra/infra.test.ts, infra-l2-outbound-proxy/template.yaml, src/tests/api/poStubAPI.test.ts, src/tests/utils/ApiTestSteps.ts
Restored L2-outbound-proxy to use PO location API and added skip flag for PO mock API tests, until deployment pipelines for the PO stub are in place
[KIWI-948](https://govukverify.atlassian.net/browse/KIWI-948)
[KIWI-948]: https://govukverify.atlassian.net/browse/KIWI-948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-948] - F2F | BE | Create Mock for the Post Office Lookup

src/tests/utils/ApiTestSteps.ts, test-harness/test-harness-spec.yaml
Re-renables sigv4 in F2F
To secure our test harness endpoints
- [KIWI-1267](https://govukverify.atlassian.net/browse/KIWI-1267)
[KIWI-1267]: https://govukverify.atlassian.net/browse/KIWI-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1267] re-renables sigv4 in F2F

src/services/F2fService.ts, src/tests/unit/SessionConfigHandler.test.ts, src/tests/unit/services/F2fService.test.ts, src/utils/Constants.ts
Adds new method to obfuscate TxMA Events before logging them out in Splunk everytime we send a TxMA Event
**Test Event**
``{
"client_id":"ipv-core-stub",
"component_id":"https://XXX-c.env.account.gov.uk",
"event_name":"F2F_YOTI_RESPONSE_RECEIVED",
"timestamp":1684933200,
"extensions":{
"evidence":[
{
"txn":"b83d54ce-1565-42ee-987a-97a1f48f27dg"
}
],
"post_office_details":[
{
"address":"1 The Street, Funkytown",
"location":[
{
"latitude":0.34322,
"longitude":-42.48372
}
],
"post_code":"SW19 4NS"
}
]
},
"user":{
"govuk_signin_journey_id":"sdfssg",
"ip_address":"127.0.0.1",
"persistent_session_id":"sdgsdg",
"session_id":"RandomF2FSessionID",
"user_id":"sub"
},
"restricted":{
"passport":[
{
"documentType":"PASSPORT"
}
]
}
}``
**obfuscated value**
=> [KIWI-1363] Add new obfuscateJSONValues method and log out obfuscated TxMA Events

test-harness/template.yaml
Set `AlwaysDeploy: true` for test harness api gateway definition
To redeploy even if changes aren't detected (api gateway is currently using the wrong role)
=> [KIWI-1134] - Forcing test harness apigw redeploy

deploy/template.yaml
- Integrate Lambda functions to ingest metrics in dynatrace 
- Add dyntrace SSM parameters and inject lambda logs to dynatrace
- This will allow dynatrace to get lambda metric from the F2F service
- [KIWI-1488](https://govukverify.atlassian.net/browse/KIWI-1488)
[KIWI-1488]: https://govukverify.atlassian.net/browse/KIWI-1488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1488:Enable Lambda metrics in Dynatrace

deploy/template.yaml
- Existing 4xx and 5xx alarms does not create invocations and errors.
- ApiName is configured wrong due to which invocations does not happen
- changed to get ApiId to configure the API gateway
- Configured the 5xx and 4xx errors alarms with ApiId
- ApiName configured incorrect causes a issue with getting invocations
- [KIWI-1497](https://govukverify.atlassian.net/browse/KIWI-1497)
[KIWI-1457]: https://govukverify.atlassian.net/browse/KIWI-1457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KIWI-1497]: https://govukverify.atlassian.net/browse/KIWI-1497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1497: Fix 4xx and 5xx error alarms with ApiId

deploy/template.yaml
Remove the GovNotifyThrottleAlarm as this is causing panic
Triggered alarm on di-2nd-line
- [KIWI-1544](https://govukverify.atlassian.net/browse/KIWI-1544)
[KIWI-1544]: https://govukverify.atlassian.net/browse/KIWI-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1544: Remove GovNotifyThrottleAlarm  attached to SQS

deploy/template.yaml
Removed the GovNotifyThrottleAlarm
Removed the GovNotifyThrottleAlarm
- [KIWI-1544](https://govukverify.atlassian.net/browse/KIWI-1544)
[KIWI-1544]: https://govukverify.atlassian.net/browse/KIWI-1544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1544: Remove GovNotifyThrottleAlarm attached to SQS

.github/dependabot.yml
Add dependabot file(sonarcloud was already excluded in https://github.com/govuk-one-login/ipv-cri-f2f-api/pull/298)
Dependabot secrets will need to be added separately according to https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3473244443/Dependabot+and+GitHub+secrets
Dependabot is an automated tool that helps manage dependencies and keep them up to date. This is recommended by the [identity team manual](https://team-manual.account.gov.uk/development-standards-processes/dependabot/). Configuration of the tool in BAV API workflows was missed during the initial repository setup so is added as part of this ticket.
- [IPS-528] (https://govukverify.atlassian.net/browse/IPS-528)
- [KIWI-1533](https://govukverify.atlassian.net/browse/KIWI-1533)
[IPS-528]: …
=> IPS-528: Add dependabot

src/services/DocumentSelectionRequestProcessor.ts, src/tests/unit/data/txmaEvent.ts
Update `F2F_YOTI_START` TxMA event in `/documentSelection` lambda with nameParts 
- [KIWI-1580](https://govukverify.atlassian.net/browse/KIWI-1580)
[KIWI-1580]: https://govukverify.atlassian.net/browse/KIWI-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1580] - F2F | BE | Include nameParts in F2F_YOTI_START

deploy/f2f-spec.yaml
Changed OpenAPI spec for /documentSelection endpoint, to allow additional attributes in the payload
To allow merging of [KIWI-1475](https://govukverify.atlassian.net/browse/KIWI-1475) without causing breaking changes
FE: [KIWI-1475](https://govukverify.atlassian.net/browse/KIWI-1475)
BE: [KIWI-1546](https://govukverify.atlassian.net/browse/KIWI-1546)
[KIWI-1475]: https://govukverify.atlassian.net/browse/KIWI-1475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KIWI-1475]: https://govukverify.atlassian.net/browse/KIWI-1475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KIWI-1546]: https://govukverify.atlassian.net/browse/KIWI-1546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
=> [KIWI-1546] - Allow additional properties in /docSelect payload

src/tests/utils/ApiTestSteps.ts
Fix for [KIWI-1413](https://govukverify.atlassian.net/browse/KIWI-1413)
Added new line to include missing import, this is causing api tests to fail in the pipeline
[KIWI-1413]: https://govukverify.atlassian.net/browse/KIWI-1413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1413] - Add missing import to ApiTestSteps

src/services/YotiSessionCompletionProcessor.ts, src/tests/api/CallbackApi.test.ts, src/tests/api/HappyPath.test.ts, src/tests/data/vcValidationData.json, src/tests/unit/data/txmaEvent.ts, src/tests/unit/services/YotiSessionCompletionProcessor.test.ts, src/tests/unit/utils/YotiCallbackUtils.ts, yoti-stub/src/data/getMediaContent/gbDriversLicenseMissingFormatedAddressResponse.ts, yoti-stub/src/services/YotiRequestProcessor.ts, yoti-stub/src/utils/Constants.ts
Make formatted_address optional while generating TXMA event.
Yoti mock updated with new code- 0003 to test UK DL without structured_postal_address in the media response.
Unit-tests added to test these negative cases
https://govukverify.atlassian.net/wiki/spaces/FTFCRI/pages/3557818744/Yoti+Journey+4+Scenarios updated with new yoti mock code- 0003
Fixes the error which occurs when this field is missing in the media response for a yoti-session
- [KIWI-1701](https://govukverify.atlassian.net/browse/KIWI-1701)
Evidence of successful TXMA event generation which does not include the fullAddress incase formatted_address field is missing or structured_postal_address field is missing in the documentFields received from Yoti media endpoint.
Api tests passing with theses changes as well, evidence …
=> [KIWI-1701] Make formatted_address optional

src/tests/api/UnhappyPath.test.ts
Unhappy Path Test Results: 
Re-enable failed /session endpoint Happy Path test with updated logic
After investigation - we need to remove yotiMockId from shared_claims for test to pass
- [KIWI-1750](https://govukverify.atlassian.net/browse/KIWI-1750)
[KIWI-1750]: https://govukverify.atlassian.net/browse/KIWI-1750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Re-enabled failed UnhappyPath /session Endpoint test

test-harness/test-harness-spec.yaml
Add new endpoint to Test Harness Spec
- getSessionByState
Support E2E testing of abort logic - state value exposed in FE abort journey but not authorizationCode
New endpoint needed to get session data using state
- [KIWI-1863](https://govukverify.atlassian.net/browse/KIWI-1863)
[KIWI-1863]: https://govukverify.atlassian.net/browse/KIWI-1863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1863: Update Test Harness Spec - /getSessionByState endpoint

deploy/template.yaml, yoti-stub/template.yaml
Fixes broken yoti-stub deployment
=> Remove IsNotProdLikeEnvironment condition from yoti-stub pipeline

deploy/template.yaml
Removes Concurrency & Throttle alarms against Expired Session lambda
=> Remove alarms for ExpiredSessions lambda

deploy/template.yaml, src/tests/infra/template.test.ts
Allows the IAM Role assumed by the CodePipeline testing stage to invoke the ExpiredSession Function, enabling automated testing.
Resource-based permissions to allow Lambda:invoke on the ExpiresSession Function granted to the deployment pipeline `TestRole`.
Enable automated testing as part of the deployment pipeline
https://govukverify.atlassian.net/browse/IPS-902
=> IPS-901: grant pipeline test role Lambda:invoke on ExpiredSession Function

src/services/AbortRequestProcessor.ts, src/tests/data/F2F_CRI_SESSION_ABORTED_SCHEMA.json
Add missing govuk_signin_journey_id field in F2F_CRI_SESSION_ABORTED
Issue raised where user triggered event F2F_CRI_SESSION_ABORTED on a front end staging stub and have found that the inbound event does not contain a "$.user.govuk_signin_journey_id" value
- [KIWI-1947](https://govukverify.atlassian.net/browse/KIWI-1947)
[KIWI-1947]: https://govukverify.atlassian.net/browse/KIWI-1947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1947 - Add missing govuk_signin_journey_id field in F2F_CRI_SESSION_ABORTED Event

deploy/template.yaml
Amended condition for ExpiredSession Function test action invoke permission.
This was mistakenly changed during an [unrelated PR here.](https://github.com/govuk-one-login/ipv-cri-f2f-api/pull/544/files#diff-aa838e3312dccda3e0f52cfcf60738f956197278c3330ed38f1cbc8cd9e977d1L3240)
Condition was originally added [here](https://github.com/govuk-one-login/ipv-cri-f2f-api/pull/552/files#diff-aa838e3312dccda3e0f52cfcf60738f956197278c3330ed38f1cbc8cd9e977d1R3096)
=> Fix for ExpiredSession Function test action invoke permission

.github/workflows/pull-request-sonar.yml, .github/workflows/run-unit-tests.yml, .github/workflows/scan-repo.yml, .gitignore, sonar-project.properties, src/tsconfig.json
Added github actions to run sonar on pushes to main
So that we can effectively monitor Kiwi services
=> KIWI-1958: Added sonar action for main branch

deploy/template.yaml
- Add F2F CRI alarms to the pager duty topic. This will publish on the topic when the alarm is triggered and pager duty will be triggered.
- Add F2F CRI alarms to the pager duty topic to publish the topic
- Add F2F CRI alarms to the pager duty topic to publish the topic
- [IPS-1181](https://govukverify.atlassian.net/browse/IPS-1181)
[IPS-1181]: https://govukverify.atlassian.net/browse/IPS-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-1181: Subscribe F2F CRI alarms to the pager duty topic

deploy/f2f-spec.yaml
Add max length validation to integers in /documentSelection Payload (longitude + latitude) 
Latitude: 
minimum: -90
maximum: 90
multipleOf: 0.0000000001 (max 10 decimal places) **REMOVED**
Longitude:
minimum: -180
maximum: 180
multipleOf: 0.0000000001 (max 10 decimal places)  **REMOVED**
- [KIWI-1987](https://govukverify.atlassian.net/browse/KIWI-1987)
[KIWI-1987]: https://govukverify.atlassian.net/browse/KIWI-1987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1987: Integer maxLength test

.github/workflows/run-unit-tests.yml, .github/workflows/scan-repo.yml, .pre-commit-config.yaml, .pre-commit-search-and-replace.yaml
EOL on the 5th December 2024
Also updated version of Sonar Cloud as it needs to use download-artifact v4 as well
The Search and Replace pre-commit hook was failing due to 
empty config so I put in a placeholder
https://govukverify.atlassian.net/browse/PSREDEV-1911
https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new
https://github.com/actions/download-artifact?tab=readme-ov-file#v4---whats-new
Updated GH actions
V3 being EOLed 5th Dec
https://govukverify.atlassian.net/browse/PSREDEV-1911
=> PSREDEV-1911-dev-platform-support-request-adam-higginson

src/package-lock.json
Ran `npm install` in order to update `package-lock.json` file after multiple dependency updates were made in https://github.com/govuk-one-login/ipv-cri-f2f-api/pull/647
To maintain a current package-lock file, and fix failing deployments
[KIWI-1995](https://govukverify.atlassian.net/browse/KIWI-1995)
[KIWI-1995]: https://govukverify.atlassian.net/browse/KIWI-1995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1995] - Update package-lock file

src/package.json
Remove Callback tests from api-third-party-traffic script
Callback tests incorrectly added to npm run script
=> Update Third Party Traffic Script to skip Unhappy Path Tests

traffic-tests/run-tests.sh
- Running api test in parallel causes random 5xx errors. The issue is caused intermittently due to which some inconsistencies in the deployment. 
- Added the tests in serial to run the time of deployment which on running 4 times for around 10 minutes for the deployment duration.
- Changed the tests to serial as often caused 5xx error. 
- [IPS-1247](https://govukverify.atlassian.net/browse/IPS-1247)
[IPS-1247]: https://govukverify.atlassian.net/browse/IPS-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-1247: Run tests in serial as parallel tests causes 5xx error

deploy/template.yaml
Updated TTLs to values pre PCL go live
To fix a bug identified in production
=> KIWI-2183: Reverting auth TTL values set incorrectly following PCL go live

f2f-ipv-stub/src/handlers/startF2fCheck.ts, src/services/DocumentSelectionRequestProcessor.ts, src/services/GenerateYotiLetterProcessor.ts, src/services/SendEmailService.ts, src/services/ThankYouEmailProcessor.ts, src/services/YotiService.ts, src/services/YotiSessionCompletionProcessor.ts, src/tests/api/backend/HappyPath.test.ts, src/tests/data/F2F_YOTI_PDF_LETTER_POSTED.json, src/tests/data/addressSessionPayload.json, src/tests/data/exampleStubPayload.json, src/tests/data/thinFilePayload.json, src/tests/unit/SendToGovNotifyHandler.test.ts, src/tests/unit/data/documentSelection-events.ts, src/tests/unit/services/YotiService.test.ts
Moved Yoti base url from constructor into method parameters so it can be updated as part of test data strategy
To allow multiple tests to be run together as part of canaries
=> KIWI-2089: Moved dynamic value yoti base url out of the yoti service constructor

src/tests/api/ApiTestSteps.ts, src/tests/api/types.ts
Remove yotiMockId from shared_claims for third-party API tests
- [KIWI-2170](https://govukverify.atlassian.net/browse/KIWI-2170)
[KIWI-2170]: https://govukverify.atlassian.net/browse/KIWI-2170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-2170: Third-Party Test Update - Remove yotiMockId

deploy/template.yaml, src/GeneratePrintedLetterHandler.ts, src/services/EnvironmentVariables.ts, src/services/pdfGenerationService.ts
Update generatePrintedLetter lambda env vars + add check in environmentVariables constructor for related service enum
To fix errors displaying dates in the printed customer letter
- [KIWI-2171](https://govukverify.atlassian.net/browse/KIWI-2171)
[KIWI-2171]: https://govukverify.atlassian.net/browse/KIWI-2171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2171] - F2F | PCL | Investigate and fix 'Invalid Date' appearing on Cover Letter

src/services/AbortRequestProcessor.ts, src/services/AccessTokenRequestProcessor.ts, src/services/AddressLocationsProcessor.ts, src/services/AuthorizationRequestProcessor.ts, src/services/DocumentSelectionRequestProcessor.ts, src/services/ExpiredSessionsProcessor.ts, src/services/F2fService.ts, src/services/GeneratePrintedLetterProcessor.ts, src/services/GenerateYotiLetterProcessor.ts, src/services/PdfService.ts, src/services/PersonInfoRequestProcessor.ts, src/services/ReminderEmailProcessor.ts, src/services/SendEmailProcessor.ts, src/services/SendEmailService.ts, src/services/SendToGovNotifyService.ts, src/services/SessionConfigRequestProcessor.ts, src/services/SessionRequestProcessor.ts, src/services/ThankYouEmailProcessor.ts, src/services/UserInfoRequestProcessor.ts, src/services/YotiSessionCompletionProcessor.ts, src/services/pdfGenerationService.ts, src/tests/unit/services/AbortRequestProcessor.test.ts, src/tests/unit/services/DocumentSelectionRequestProcessor.test.ts, src/tests/unit/services/F2fService.test.ts, src/tests/unit/services/PdfGenerationService.test.ts, src/tests/unit/services/SendEmailProcessor.test.ts, src/tests/unit/services/SessionRequestProcessor.test.ts, src/tests/unit/services/ThankYouEmailProcessor.test.ts, src/tests/unit/services/UserInfoRequestProcessor.test.ts, src/tests/unit/services/YotiSessionCompletionProcessor.test.ts
Added metrics to cover 6 key aspects of the journey.
1. When a user sessions created successfully in F2F
2. When a user clicks submit on check details page
3. When a user is sent their confirmation email
4. When /userInfo endpoint is hit by IPV core to retrieve a pending VC
5. When a user goes to PO and document is uploaded to Yoti
6. When checks are successfully carried out on Yoti document
As well as key state transitions:
- F2F_SESSION_CREATED
- F2F_YOTI_SESSION_CREATED 
- F2F_AUTH_CODE_ISSUED 
- F2F_ACCESS_TOKEN_ISSUED
- F2F_YOTI_SESSION_COMPLETE 
- F2F_CREDENTIAL_ISSUED 
- F2F_SESSION_ABORTED 
- F2F_CRI_SESSION_ABORTED 
- F2F_SESSION_EXPIRED 
Dashboard update to follow this PR
To allow us to more easily track F2F journeys and drop outs
=> KIWI-2188: Added metrics to track the flow of users through the F2F journery

src/tests/api/ApiTestSteps.ts, src/tests/api/backend/UnhappyPath.test.ts, src/tests/api/types.ts
Added tests for invalidKid + missingKid to BavUnhappyPath test file.
Negative testing: Key Rotation (BAV)
- [KIWI-2208](https://govukverify.atlassian.net/browse/KIWI-2208)
[KIWI-2208]: https://govukverify.atlassian.net/browse/KIWI-2208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-2206: F2F Key Rotation QA Updates

deploy/template.yaml
Updated support links in alarm descriptions
To ensure users are taken to the relevant Confluence page if support is required
- [KIWI-2285](https://govukverify.atlassian.net/browse/KIWI-2285)
[KIWI-2285]: https://govukverify.atlassian.net/browse/KIWI-2285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2285] - Live Services | Incorrect support manual links in alarm descriptions

deploy/f2f-spec.yaml, deploy/template.yaml, src/JwksHandler.ts, src/jest.setup.ts, src/tests/unit/JwksHandler.test.ts
Implemented logic of copying keys from existing jwks bucket to new f2f published keys bucket in `JwksHandler` , and pointed well-known endpoint to new jwks/json folder. 
Added unit tests
To facilitate key rotation initiative
- [KIWI-2335](https://govukverify.atlassian.net/browse/KIWI-2335)
[KIWI-2335]: https://govukverify.atlassian.net/browse/KIWI-2335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2335] - F2F | OAuth | Move public encryption keys to new S3

deploy/template.yaml
Added regional(API Gateway/Load Balancer Tags to template file
As part of transitioning FMS WAF rule enforcement from COUNT to BLOCK, Security have set up custom policies for us to apply to our resources in scope.
- [KIWI-2477](https://govukverify.atlassian.net/browse/KIWI-2477)
[KIWI-2477]: https://govukverify.atlassian.net/browse/KIWI-2477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2477] - F2F | Add FMS tags for custom WAF policy migration in lower environments

deploy/template.yaml
Added regional(API Gateway/Load Balancer Tags to template file
As part of transitioning FMS WAF rule enforcement from COUNT to BLOCK, Security have set up custom policies for us to apply to our resources in scope.
- [KIWI-2477](https://govukverify.atlassian.net/browse/KIWI-2477)
[KIWI-2477]: https://govukverify.atlassian.net/browse/KIWI-2477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2477B] - F2F | Add FMS tags for custom WAF policy migration in lower environments 
