govuk-one-login/ipv-cri-f2f-api

infra-l2-dynamo/jest.config.ts, infra-l2-dynamo/package-lock.json, infra-l2-dynamo/package.json, infra-l2-dynamo/src/tests/infra/infra.test.ts, infra-l2-dynamo/template.yaml, infra-l2-dynamo/tsconfig.json, infra-l2-kms/.gitignore, infra-l2-kms/jest.config.ts, infra-l2-kms/package-lock.json, infra-l2-kms/package.json, infra-l2-kms/src/tests/infra/infra.test.ts, infra-l2-kms/template.yaml, infra-l2-kms/tsconfig.json
F2F-96 and F2F-72
Initial commit of KMS and DynamoDB templates (copied from CIC repo)
L2 stacks requirement
=> F2F-96 and F2F-72: Add kms, dyndb templates

.github/workflows/post-merge-waf-build.yml, .github/workflows/post-merge-waf-dev.yml, infra-l2-waf/README.md, infra-l2-waf/template.yaml
Add WAF github actions workflows for DEV and BUILD
Add WAF template
- [F2F-27](https://govukverify.atlassian.net/browse/F2F-27)
- [PLAT-854](https://govukverify.atlassian.net/browse/PLAT-854)
[F2F-316]: https://govukverify.atlassian.net/browse/F2F-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PLAT-854]: https://govukverify.atlassian.net/browse/PLAT-854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-27]: https://govukverify.atlassian.net/browse/F2F-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PLAT-854: Add WAF workflows and template

.github/workflows/post-merge-package-to-dev.yml
- [F2F-184](https://govukverify.atlassian.net/browse/F2F-184)
[F2F-184]: https://govukverify.atlassian.net/browse/F2F-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-184a -  Adding post merge dev file

.github/workflows/pull-request-Dynamo.yml, .github/workflows/pull-request-KMS.yml, .github/workflows/pull-request-WAF.yml, .github/workflows/pull-request.yml, .secrets.baseline
Modifying detect secret to scan all file as part of pre-commit
=> Modifying detect secret to scan all file

deploy/template.yaml
Added cron job expression in JsonkeysFunction
To run Lambda function every hour
- [F2F-352](https://govukverify.atlassian.net/browse/F2F-352)
[F2F-352]: https://govukverify.atlassian.net/browse/F2F-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-352 Added cron job expression in JsonkeysFunction

yoti-stub/yoti-spec.yaml
Adding in openapi spec for Instructions and Sessions, including only the relevant endpoints in use by F2F flow
To enable stubbing Yoti calls
- [F2F-446](https://govukverify.atlassian.net/browse/F2F-446)
[F2F-446]: https://govukverify.atlassian.net/browse/F2F-446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-446] Yoti openapi spec

f2f-ipv-stub/src/handlers/startF2fCheck.ts, f2f-ipv-stub/template.yaml
Fixes incorrect target url for jwks in stub
=> Fix incorrect target url for jwks in stub

f2f-ipv-stub/template.yaml
Rename env var in stub template
=> Rename env var in stub template

.github/workflows/post-merge-yoti-stub-to-build.yml, .github/workflows/post-merge-yoti-stub-to-dev.yml
Adding signing profile for Yoti stub so MockYotiStub lambda can be signed
=> [F2F-446]: Adding signing profile for Yoti stub

adr/0001-YotiIntegration.md, adr/template.md
ADR to capture the design and research process for our integration with Yoti.
- [F2F-456](https://govukverify.atlassian.net/browse/F2F-456)
[F2F-456]: https://govukverify.atlassian.net/browse/F2F-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ADR: Yoti integration infrastructure

.github/workflows/post-merge-yoti-stub-to-dev.yml, yoti-stub/template.yaml
Correcting Yoti stub subdomain name for build
=> [F2F-446]: Correcting Yoti stub subdomain name for build

f2f-ipv-stub/template.yaml
=> Updating FE url in stub

deploy/template.yaml
Removing LanguageExtensions from template
- [F2F-509](https://govukverify.atlassian.net/browse/F2F-509)
[F2F-509]: https://govukverify.atlassian.net/browse/F2F-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-509 Removing LanguageExtensions from template

deploy/template.yaml, src/models/enums/YotiSessionState.ts, src/services/DocumentSelectionRequestProcessor.ts, src/services/F2fService.ts, src/tests/unit/services/DocumentSelectionRequestProcessor.test.ts, src/tests/unit/services/F2fService.test.ts
Save yotiSessionID to sessionTable
=> Save yotiSessionID to sessionTable

yoti-stub/samconfig.toml, yoti-stub/src/MockYotiSessionHandler.ts, yoti-stub/src/data/driversLicenseResponse.ts, yoti-stub/src/data/responses.ts, yoti-stub/src/models/enums/ResourcesEnum.ts, yoti-stub/src/services/YotiRequestProcessor.ts, yoti-stub/template.yaml, yoti-stub/yoti-spec.yaml
This creates a GET /sessions/{sessionId} endpoint for the Yoti Stub and returns a 200 response and body for 0000 (passport) and 0001 (driving license), and the relevant bad responses listed in [F2F-437](https://govukverify.atlassian.net/browse/F2F-437). Examples of the responses from the API calls: 
- [F2F-437](https://govukverify.atlassian.net/browse/F2F-437)
[F2F-437]: https://govukverify.atlassian.net/browse/F2F-437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-437]: https://govukverify.atlassian.net/browse/F2F-437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-437] - Yoti Stub GET /sessions/{sessionId}

sonar-project.properties
To modify sonar settings for code coverage information
Can see it adding coverage information on local sonar instance
=> Modifying sonar properties for adding coverage info

sonar-project.properties
Added an extra line to test the sonarQube issues. 
Additional line will invoke the workflow to test the second commit invoke the code coverage
- [F2F-XXX](https://govukverify.atlassian.net/browse/F2F-XXX)
=> F2F-100:Create a pull request to test the changes

deploy/template.yaml, src/services/AccessTokenRequestProcessor.ts, src/services/AuthorizationRequestProcessor.ts, src/services/DocumentSelectionRequestProcessor.ts, src/services/F2fService.ts, src/services/UserInfoRequestProcessor.ts, src/services/YotiCallbackProcessor.ts, src/tests/infra/template.test.ts, src/tests/unit/services/AccessTokenRequestProcessor.test.ts, src/tests/unit/services/DocumentSelectionRequestProcessor.test.ts, src/tests/unit/services/YotiCallbackProcessor.test.ts, src/utils/TxmaEvent.ts
- Ensuring auth session state is verified as being the expected one as per [Backend state machine in F2F design](https://github.com/alphagov/digital-identity-architecture/blob/rfc36-facetoface-design/rfc/0046-facetoface-design.md#backend-state-machine) for /documentSelection, /authorization, /userInfo, /token, /callback before processing request to that endpoint to prevent multiple updates to the same session 
- Fixing subdomain for API to be `api.<env> `for Build onwards
- Setting `user_id` to be same as `subject` from the incoming JAR instead of `sessionId`
- [F2F-588](https://govukverify.atlassian.net/browse/F2F-588)
- [F2F-587](https://govukverify.atlassian.net/browse/F2F-587)
**Authorization**
**DocumentSelection**
**Token**
[F2F-588]: …
=> [F2F-587] Fixing multiple Yoti Sessions created for same sessionId

deploy/template.yaml
Enable debug logging as seems /session is failing on Build only and unable to see any logs in INFO to understand the cause
=> [F2F-578] Enable debug logging on all environments

.github/workflows/pull-request-sonar.yml
- Fix for Sonar Scan Code coverage 0% on Backend repos.
- Removed the test infra before run the sonar scan 
- [F2F-603](https://govukverify.atlassian.net/browse/F2F-603)
[F2F-603]: https://govukverify.atlassian.net/browse/F2F-603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-603: Fix for Code coverage issue oh the sonar scan report

yoti-stub/src/MockYotiSessionHandler.ts, yoti-stub/src/data/getMediaContent/espPassportResponse.ts, yoti-stub/src/data/getMediaContent/euDriversLicenseResponse.ts, yoti-stub/src/data/getMediaContent/gbDriversLicenseResponse.ts, yoti-stub/src/data/getMediaContent/gbPassportResponse.ts, yoti-stub/src/data/getMediaContent/getMediaContent400.ts, yoti-stub/src/data/getMediaContent/getMediaContent401.ts, yoti-stub/src/data/getMediaContent/getMediaContent404.ts, yoti-stub/src/data/getMediaContent/nldNationalId.ts, yoti-stub/src/data/getSessions/aiFailManualFail.ts, yoti-stub/src/data/getSessions/aiFailManualPass.ts, yoti-stub/src/data/getSessions/aiPass.ts, yoti-stub/src/data/getSessions/differentPersonResponse.ts, yoti-stub/src/data/getSessions/expiredPassport.ts, yoti-stub/src/data/getSessions/nfcResponse.ts, yoti-stub/src/data/getSessions/tamperedDocumentResponse.ts, yoti-stub/src/models/enums/ResourcesEnum.ts, yoti-stub/src/services/YotiRequestProcessor.ts, yoti-stub/template.yaml, yoti-stub/yoti-spec.yaml
Added new completed YOTI sessions from GDrive
https://govukverify.atlassian.net/browse/F2F-569
=> [F2F-569] - Enhance the Yoti mock for the callback journey

f2f-ipv-stub/src/handlers/startF2fCheck.ts
YOTI Api tests were failing as result of this PR : https://github.com/alphagov/di-ipv-cri-f2f-api/pull/92
Updating API tests to match the new logic
=> [F2F 714] - Fix Yoti API Tests

deploy/template.yaml, yoti-stub/template.yaml
Deploys Yoti Mock to staging
https://govukverify.atlassian.net/browse/F2F-710
=> [F2F-710] - Deploy Yoti Mock to staging

infra-l2-dynamo/template.yaml
Removes the yoitiSessionId-Index to fix dynamoDB deployment
=> [F2F-731] Fix Deployment of DynamoDB Stack

infra-l2-dynamo/template.yaml
[[F2F-731] Update NonKeyAttributes for yotiSessionId](https://github.com/alphagov/di-ipv-cri-f2f-api/commit/ad2b8e9983a4cbbc4c04b4d7ee3ffdda293d5ae5)
[F2F-731]: https://govukverify.atlassian.net/browse/F2F-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-731] Update NonKeyAttributes for yotiSessionId

deploy/template.yaml, src/services/YotiService.ts
Update YOTIBASEURL for Build & staging
Add logging around getRSASignatureForMessage to catch any issues with private key encryption
https://govukverify.atlassian.net/browse/F2F-746
=> [F2F] - Enable E2E flow on Build

deploy/template.yaml
[JIRA Ticket ](https://govukverify.atlassian.net/browse/F2F-749)
=> [F2F-749] Modifying redirect urls as per integ testing

yoti-stub/src/data/getSessions/aiPass.ts, yoti-stub/src/data/getSessions/responses.ts, yoti-stub/src/services/YotiRequestProcessor.ts, yoti-stub/src/utils/Constants.ts
Updated the Yoti Mock to add the missing scenarios for non-uk passport and UK DL 
https://govukverify.atlassian.net/wiki/spaces/FTFCRI/pages/3557818744/Yoti+Journey+4+Scenarios
=> [F2F-747] - Enhance Yoti mock with additional Scenarios for UK DL and Non-UK Passports

yoti-stub/src/services/YotiRequestProcessor.ts, yoti-stub/src/utils/Constants.ts
- [F2F-XXX](https://govukverify.atlassian.net/browse/F2F-XXX)
=> [F2F-747] - Enhance Yoti Mock

src/services/VerifiableCredentialService.ts, src/tests/unit/services/VerifiableCredentialService.test.ts, src/tests/unit/services/YotiCallbackProcessor.test.ts
- [F2F-771](https://govukverify.atlassian.net/browse/F2F-771)
[F2F-771]: https://govukverify.atlassian.net/browse/F2F-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-771]: Removing urn:uuid prepended to the subject in generated VC

.github/pull_request_template.md
Add check in PR template for PII data in log
To remind us when raising a PR
=> [F2F]: Add check in PR template

deploy/f2f-spec.yaml, src/models/YotiPayloads.ts, src/services/YotiService.ts, src/tests/unit/services/YotiService.test.ts
Reverting changes made in PR for F2F-909
F2F FE pipeline on Prod not getting triggered, hence reverting the changes to the BE /documentSelection payload to not expect `name` as required property
- [F2F-909](https://govukverify.atlassian.net/browse/F2F-909)
[F2F-909]: https://govukverify.atlassian.net/browse/F2F-909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-909]: reverting changes in 909

.github/workflows/post-merge-dynamo-to-build.yml, .github/workflows/post-merge-dynamo-to-dev.yml, .github/workflows/post-merge-ipv-stub-package-to-build.yml, .github/workflows/post-merge-ipv-stub-package-to-dev.yml, .github/workflows/post-merge-kms-build.yml, .github/workflows/post-merge-kms-dev.yml, .github/workflows/post-merge-outbound-proxy-to-build.yml, .github/workflows/post-merge-outbound-proxy-to-dev.yml, .github/workflows/post-merge-package-to-build.yml, .github/workflows/post-merge-package-to-dev.yml, .github/workflows/post-merge-yoti-stub-to-build.yml, .github/workflows/post-merge-yoti-stub-to-dev.yml, .github/workflows/pull-request-Dynamo.yml, .github/workflows/pull-request-KMS.yml, .github/workflows/pull-request-ipv-stub.yml, .github/workflows/pull-request-outbound-proxy.yml, .github/workflows/pull-request-yoti-stub.yml, .github/workflows/pull-request.yml
GHA pipeline step  `aws-actions/setup-sam@v2` failing as below:
Adding change as suggested [here](https://gds.slack.com/archives/C02R5AB0VV0/p1689611069795149)
=> [F2F]: To resolve aws-actions/setup-sam@v2 breaking

yoti-stub/src/data/getMediaContent/gbPassportResponse.ts
Changed Yoti Stub document fields to be all caps
=> F2F-963 Update name in Yoti Stub to Caps

.github/workflows/post-merge-push-test-container-to-build.yml, .github/workflows/post-merge-push-test-container-to-dev.yml
In line with the GHA workflows being bought into the test container deployment, this PR is fixing a syntax issue in the yaml file
- [F2F-931](https://govukverify.atlassian.net/browse/F2F-931)
[F2F-931]: https://govukverify.atlassian.net/browse/F2F-931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-931-fixed syntax issue for test container GHA workflows

src/tests/api/CallbackApi.test.ts, src/tests/api/DocumentSelectionHappyPath.test.ts
Suspend the BE validation checks for all tests
Suspended the BE validation checks for all tests
It was discovered that the current approach for validating BE systems using the .aws SDK via automated tests has not been done on the programme previously. 
As such, there is a requirement to temporally disable the BE checks in the pipeline until a detailed design can be thought through. 
- [F2F-978](https://govukverify.atlassian.net/browse/F2F-978)
[F2F-978]: https://govukverify.atlassian.net/browse/F2F-978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BE Test Suspensions

deploy/samconfig.toml, deploy/template.yaml, test-harness/samconfig.toml, test-harness/src/DequeueHandler.ts, test-harness/src/package-lock.json, test-harness/src/tests/unit/DequeueHandler.test.ts, test-harness/template.yaml, test-harness/test-harness-spec.yaml
=> Merge Viveaks Changes to Caitlin's 1006 branch

.github/workflows/post-merge-package-to-build.yml, .github/workflows/post-merge-package-to-dev.yml, .github/workflows/post-merge-push-test-container-to-build.yml, .github/workflows/post-merge-push-test-container-to-dev.yml, .github/workflows/post-merge-test-harness-package-to-build.yml, .github/workflows/post-merge-test-harness-package-to-dev.yml, .github/workflows/pull-request-test-harness.yml, .github/workflows/pull-request.yml, test-harness/README.md, test-harness/src/DequeueHandler.ts, test-harness/src/package-lock.json, test-harness/src/package.json, test-harness/src/tests/unit/DequeueHandler.test.ts, test-harness/template.yaml, test-harness/test-harness-spec.yaml
Adds pull request, deploy build and deploy dev workflows for test harness
To deploy the test harness when it changes
- [F2F-1058](https://govukverify.atlassian.net/browse/F2F-1058)
- Needs [F2F-1057](https://govukverify.atlassian.net/browse/F2F-1057) (secrets)
[F2F-1058]: https://govukverify.atlassian.net/browse/F2F-1058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-1057]: https://govukverify.atlassian.net/browse/F2F-1057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-1058: Test harness workflows

src/tests/api/SessionTests.test.ts, src/tests/data/addressSessionPayload.json
- [F2F-993](https://govukverify.atlassian.net/browse/F2F-993)
[F2F-993]: https://govukverify.atlassian.net/browse/F2F-993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F 993 session tests

test-harness/template.yaml
- Added permission boundary for the DynamoDbAccessRole
- Fix the DynamoDbAccessRole policies indentation errors
- Add rolename for DynamoDB access role
- [F2F-1058](https://govukverify.atlassian.net/browse/F2F-1058)
[F2F-1058]: https://govukverify.atlassian.net/browse/F2F-1058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-1058: Fix dynamodb access issues

deploy/template.yaml
Updating Test Harness URL
Tests failing in test pipeline due to incorrect baseURL
- [F2F-1102](https://govukverify.atlassian.net/browse/F2F-1102)
-
=> Updating TESTHARNESSURL

deploy/template.yaml
Build Test Harness URL Update
- [F2F-1102](https://govukverify.atlassian.net/browse/F2F-1102)
[F2F-1102]: https://govukverify.atlassian.net/browse/F2F-1102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Build URL Test Harness

yoti-stub/src/data/getMediaContent/gbPassportResponseJOYCE.ts, yoti-stub/src/services/YotiRequestProcessor.ts, yoti-stub/src/utils/Constants.ts
Added support for user: Joyce Basu in yoti stub
- [F2F-1109](https://govukverify.atlassian.net/browse/F2F-1109)
Tested by deploying on `yoti-stub-richa` stack
[F2F-1109]: https://govukverify.atlassian.net/browse/F2F-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-1109]: Update Yoti Mock to Include 1 Thin File Users

src/services/YotiCallbackProcessor.ts, src/tests/unit/data/txmaEvent.ts, src/tests/unit/services/YotiCallbackProcessor.test.ts
Reverts alphagov/di-ipv-cri-f2f-api#208
=> Revert "[F2F-1107] Updates name in TxMA F2F_CRI_VC_ISSUED event"

src/tests/api/Address.test.ts
Remove failing tests
Changes to Address logic following F2F-993, new tests added to Sessions.test.ts as part of F2F-993 PR and old tests now need to be removed
- [F2F-993](https://govukverify.atlassian.net/browse/F2F-993)
[F2F-993]: https://govukverify.atlassian.net/browse/F2F-993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> remove old address tests - F2F-993

src/services/YotiCallbackProcessor.ts, src/tests/unit/data/txmaEvent.ts, src/tests/unit/services/YotiCallbackProcessor.test.ts
Updated the name value sent in the F2F_CRI_VC_ISSUED event 
Changes requested
- [F2F-1107](https://govukverify.atlassian.net/browse/F2F-1107)
- Relies on changes from F2F-1000
[F2F-1107]: https://govukverify.atlassian.net/browse/F2F-1107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-1107] Updates name in TxMA event

src/tests/api/CallbackApi.test.ts
Remove Test Harness logic from QA tests
Test Harness logic causing issues with automated tests, not all TxMA events picked up and logged - Validated manually by @richa-misra that TxMA logs were present for failing scenarios in CloudWatch
N/A
=> Remove test harness logic

src/tests/api/CallbackApi.test.ts, src/tests/data/F2F_CRI_VC_ISSUED_SCHEMA.json
Reenable test harness logic in F2F BE tests
Issue with Test Harness resolved 
N/A
=> re-enable test harness logic

deploy/template.yaml, gov-notify-stub/template.yaml
Updating dev stub url and adding back MockGovNotifyRestApiUsagePlan for stub deployment.
=> [F2F-583] fixing pipeline issues

deploy/template.yaml
Update env variable ref for GOVUKNOTIFYAPI
Not correctly defined in template.yml causing deployment pipeline to break
N/A
=> update env variable ref for GOVUKNOTIFYAPI

deploy/template.yaml, src/tests/api/govNotifyAPI.test.ts
Disable govNotify tests
GovNotifyStub not deployed to build
N/A
=> Disable gov notify tests

src/tests/api/govNotifyAPI.test.ts
Re-enable GovNotify Tests
Build GovNotify Stub deployed
N/A
=> re-enable govNotifyStub tests

yoti-stub/src/data/getMediaContent/gbPassportResponseSUZIE.ts, yoti-stub/src/services/YotiRequestProcessor.ts, yoti-stub/src/utils/Constants.ts
Added a new happy path user for integration testing - Suzie
Evidence of the media endpoint response for this new code attached to the ticket for reference.
Ask from Integration testing team
- [F2F-1162](https://govukverify.atlassian.net/browse/F2F-1162)
[F2F-1162]: https://govukverify.atlassian.net/browse/F2F-1162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-1162] Adding new user in Yoti stub for integration testing.

infra-l2-dynamo/template.yaml
Matching DynamoDB indexes to what's currently in Prod
=> [KIWI-1212] - Updating db index to match prod

infra-l2-dynamo/template.yaml
Reverts alphagov/di-ipv-cri-f2f-api#240
=> Revert "[KIWI-1212] - Updating db index to match prod"

deploy/template.yaml
Change Reset YOTIBASEURL back to the Yoti Mock endpoint
=> Reset YOTIBASEURL back to Yoti Mock

deploy/template.yaml
=> Update YOTIBASEURL URL in Dev

src/services/AbortRequestProcessor.ts, src/tests/api/AbortApi.test.ts, src/tests/unit/services/AbortRequestProcessor.test.ts
Update response code of /abort from 301 to 200 to prevent Axios redirect
=> [KIWI-1213] Fix Users Redirected to IPV Core with OAuth server_error

deploy/template.yaml
Adding CSLS  for TriggerYotiCallbackStateMachine
=> F2F-1069 Adding CSLS for TriggerYotiCallbackStateMachine

src/services/VerifiableCredentialService.ts, src/tests/unit/services/VerifiableCredentialService.test.ts, src/tests/unit/services/YotiSessionCompletionProcessor.test.ts, src/tests/utils/ApiTestSteps.ts, src/utils/Constants.ts, src/utils/IVeriCredential.ts
Include jti in the F2F VC
Tech Debt
Evidence attached to the ticket for reference.
- [KIWI-907](https://govukverify.atlassian.net/browse/KIWI-907)
[KIWI-907]: https://govukverify.atlassian.net/browse/KIWI-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-907]Include jti in the F2F VC

src/tests/api/DocumentSelectionNegativePath.test.ts, src/tests/api/SessionNegativePath.test.ts, src/tests/api/UserInfoNegativePath.test.ts
Resolving issues with Negative Path tests
Deployment blocked by failing tests
- [KIWI-827](https://govukverify.atlassian.net/browse/KIWI-827)
[KIWI-827]: https://govukverify.atlassian.net/browse/KIWI-827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-827 Test Fixes

src/tests/api/CallbackApi.test.ts, src/tests/api/DocumentSelectionHappyPath.test.ts, src/tests/utils/ApiTestSteps.ts
Clean up of test code, reduce duplication of common logic by introducing new method to carry out all logic before /callback
Recent PR came with comments about test code duplication, picked up in a separate tasl 
N/A
=> Removing duplication in test code

src/SessionConfigHandler.ts, src/models/enums/ResourcesEnum.ts, src/tests/api/CallbackApi.test.ts, src/tests/unit/SessionConfigHandler.test.ts, src/tests/unit/services/GenerateVerifiableCredential.test.ts, src/tests/utils/ApiTestSteps.ts
Update SessionConfigHandler logic and add tests to increase file coverage
Removed resource switching and HTTP Method Checks
=> [KIWI-1209] - Update SessionConfigHandler logic and add tests

gov-notify-templates/DynamicReturnJourneyEmail
Saving contents of DynamicReturnJourneyEmail Template to repo
This is just a backup file for the template that exists in GovNotify. Not being used anywhere
=> [KIWI-1062] - Save DynamicReturnJourneyEmail Template

infra-l2-outbound-proxy/src/tests/infra/infra.test.ts, infra-l2-outbound-proxy/template.yaml
Updates post office mock proxy url
Post office mock is not working in build
=> Updates post office mock proxy url

deploy/template.yaml
Reverts govuk-one-login/ipv-cri-f2f-api#294
=> Revert "KIWI-1488:Enable Lambda metrics in Dynatrace"

src/tests/data/F2F_YOTI_START_00_SCHEMA.json, src/tests/data/F2F_YOTI_START_01_SCHEMA.json, src/tests/data/F2F_YOTI_START_02_SCHEMA.json, src/tests/data/F2F_YOTI_START_03_SCHEMA.json, src/tests/data/F2F_YOTI_START_04_SCHEMA.json, src/tests/data/F2F_YOTI_START_05_SCHEMA.json
Updating JSON Schema to contain nameParts and other TxMA validation fixes
- [KIWI-1580](https://govukverify.atlassian.net/browse/KIWI-1580)
[KIWI-1580]: https://govukverify.atlassian.net/browse/KIWI-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Kiwi 1580 QA

src/tests/api/DocumentSelectionNegativePath.test.ts, src/tests/data/dataPassportBlankFad.json, src/tests/data/dataPassportIncorrectFad.json, src/tests/data/dataPassportInvalidFadFormat.json, src/tests/data/dataPassportMissingFad.json, src/tests/data/docSelectionPayloadBrpValid.json, src/tests/data/docSelectionPayloadDriversLicenceInvalid.json, src/tests/data/docSelectionPayloadDriversLicenceValid.json, src/tests/data/docSelectionPayloadEeaIdCardValid.json, src/tests/data/docSelectionPayloadEuDriversLicenceValid.json, src/tests/data/docSelectionPayloadNonUkPassportValid.json, src/tests/data/docSelectionPayloadPassportValid.json
Update documentSelection to reflect fad_code updates
- [KIWI-1546](https://govukverify.atlassian.net/browse/KIWI-1546)
[KIWI-1546]: https://govukverify.atlassian.net/browse/KIWI-1546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1546 QA Updates

deploy/template.yaml
Added conditional logic to `POWERTOOLS_LOG_LEVEL` dependent on environment.
- [KIWI-1596](https://govukverify.atlassian.net/browse/KIWI-1596)
[KIWI-1596]: https://govukverify.atlassian.net/browse/KIWI-1596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1596] - F2F | BE | Limit logs in prod to INFO and higher

src/tests/api/DocumentSelectionNegativePath.test.ts, src/tests/data/F2F_YOTI_START_00_SCHEMA.json, src/tests/data/F2F_YOTI_START_01_SCHEMA.json, src/tests/data/F2F_YOTI_START_02_SCHEMA.json, src/tests/data/F2F_YOTI_START_03_SCHEMA.json, src/tests/data/F2F_YOTI_START_04_SCHEMA.json, src/tests/data/F2F_YOTI_START_05_SCHEMA.json, src/tests/data/dataPassportBlankFad.json, src/tests/data/dataPassportIncorrectFad.json, src/tests/data/dataPassportInvalidFadFormat.json, src/tests/data/dataPassportMissingFad.json, src/tests/data/docSelectionPayloadBrpValid.json, src/tests/data/docSelectionPayloadDriversLicenceInvalid.json, src/tests/data/docSelectionPayloadDriversLicenceValid.json, src/tests/data/docSelectionPayloadEeaIdCardValid.json, src/tests/data/docSelectionPayloadEuDriversLicenceValid.json, src/tests/data/docSelectionPayloadNonUkPassportValid.json, src/tests/data/docSelectionPayloadPassportValid.json
Update documentSelection to reflect fad_code updates
- [KIWI-1546](https://govukverify.atlassian.net/browse/KIWI-1546)
[KIWI-1546]: https://govukverify.atlassian.net/browse/KIWI-1546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1546 QA Updates #352

f2f-ipv-stub/src/handlers/startF2fCheck.ts
Pass custom frontend URL to IPV Stub
=> [KIWI-1559] - Enable use of custom frontend urls

package-lock.json, src/tests/api/Yoti.test.ts, src/tests/utils/ApiTestSteps.ts
Updated tests for YOTI mock
Changes to YOTI mock caused API test failures
[KIWI-1477](https://govukverify.atlassian.net/browse/KIWI-1477)
[KIWI-1477]: https://govukverify.atlassian.net/browse/KIWI-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1477] - Fix failing API tests

deploy/template.yaml, run-tests.sh, src/tests/api/CallbackApi.test.ts, src/tests/utils/ApiConstants.ts, src/tests/utils/ApiTestSteps.ts
Add logic to check for Additional Claims in VC
- [KIWI-1413](https://govukverify.atlassian.net/browse/KIWI-1413)
[KIWI-1413]: https://govukverify.atlassian.net/browse/KIWI-1413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1413 QA Updates

src/tests/data/vcValidationData.json
Update DOC_NUMBER_INVALID Contra Indicator from D02 to D14
"A piece of planned work that would see us change our "DOC_NUMBER_INVALID" error in F2F from a D02 CI to a D14 CI."
- [KIWI-1638](https://govukverify.atlassian.net/browse/KIWI-1638)
[KIWI-1638]: https://govukverify.atlassian.net/browse/KIWI-1638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update DOC_NUMBER_INVALID Contra Indicator

run-tests.sh, src/check-logs.sh, src/package.json, src/tests/data/exampleStubPayload.json
Adds check-logs script that scans logs for PII that is used in automation testing
Catch PII in our dev before deployment
- [KIWI-1526](https://govukverify.atlassian.net/browse/KIWI-1526)
Evidences attached for reference:
When No PII was found:
When PII was found:
[KIWI-1526]: https://govukverify.atlassian.net/browse/KIWI-1526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1526] Adds PII check for automation

deploy/template.yaml
Update ReminderEmail cron to be hourly
=> [KIWI-1651] Update ReminderEmail cron to be hourly

deploy/template.yaml
=> [KIWI-1640] Updating TTL in dev to 1 day

src/services/SessionRequestProcessor.ts
Add govuk_signin_journey_id to logs earlier
=> [KIWI-1689] Add govuk_signin_journey_id to logs earlier

run-tests-locally.sh, run-tests.sh
Update run-tests logic to output report for failed test runs
Store report for failed runs in CodeBuild
- [KIWI-1685](https://govukverify.atlassian.net/browse/KIWI-1685)
[KIWI-1685]: https://govukverify.atlassian.net/browse/KIWI-1685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1685 QA F2F

src/tests/api/CallbackApi.test.ts, src/tests/api/HappyPath.test.ts, src/tests/data/vcValidationData.json
Add new test to validate successful documentSelection response when formatted_address field is missing
- [KIWI-1701](https://govukverify.atlassian.net/browse/KIWI-1701)
[KIWI-1701]: https://govukverify.atlassian.net/browse/KIWI-1701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Kiwi 1701 QA

src/services/SendEmailService.ts
=> Format SendEmailService

f2f-ipv-stub/package.json, f2f-ipv-stub/src/auth.types.ts, f2f-ipv-stub/src/handlers/startF2fCheck.ts
Refactor IPVStub lambda and add new clientID for E2E testing changes
=> [KIWI-1778] Refactor IPVStub and add clientID

deploy/template.yaml
=> Fix env vars

run-tests.sh
Update to run-tests.sh script to fix Yoti stub and F2F Api pipeline test config
Broken logic in run-tests.sh script merged to main as part of KIWI-1880
=> F2F Pipeline Test Fixes

src/jest.config.ts, src/package-lock.json, src/package.json
Added test report generation for Jest.
- [KIWI-1898](https://govukverify.atlassian.net/browse/KIWI-1898)
[KIWI-1898]: https://govukverify.atlassian.net/browse/KIWI-1898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Jest.config with html reporter in F2F

run-tests.sh
Update IPV Stub URL to fix failing tests
100/103 pipeline tests failing 
=> F2F Pipeline Test Fix: run-tests.sh updates

run-tests.sh
=> Fix run-tests.sh script

run-tests.sh
Reverts govuk-one-login/ipv-cri-f2f-api#501
=> Revert "Fix run-tests.sh script"

.github/workflows/post-merge-deploy-api.yml, .github/workflows/post-merge-deploy-dynamo.yml, .github/workflows/post-merge-deploy-govnotify-stub.yml, .github/workflows/post-merge-deploy-ipv-stub.yml, .github/workflows/post-merge-deploy-kms.yml, .github/workflows/post-merge-deploy-outbound-proxy.yml, .github/workflows/post-merge-deploy-postoffice-mock.yml, .github/workflows/post-merge-deploy-test-container.yml, .github/workflows/post-merge-deploy-test-harness.yml, .github/workflows/post-merge-deploy-yoti-stub.yml, README.md, f2f-ipv-stub/README.md, gov-notify-stub/README.md, infra-l2-dynamo/README.md, infra-l2-kms/README.md, infra-l2-outbound-proxy/README.md, post-office-stub/README.md, post-office-stub/src/README.md, src/README.md, test-harness/README.md, yoti-stub/README.md
=> [Kiwi 1908] Refactor post merge GHA jobs

run-tests.sh
Fixes the Yoti Stub and F2F API pipelines
=> Update run-test script

deploy/template.yaml
Reverts govuk-one-login/ipv-cri-f2f-api#500
=> Revert "Remove IsNotProdLikeEnvironment condition from yoti-stub pipeline"

.github/workflows/post-merge-deploy-all.yml, .github/workflows/post-merge-deploy-api.yml, .github/workflows/post-merge-deploy-dynamo.yml, .github/workflows/post-merge-deploy-govnotify-stub.yml, .github/workflows/post-merge-deploy-ipv-stub.yml, .github/workflows/post-merge-deploy-kms.yml, .github/workflows/post-merge-deploy-outbound-proxy.yml, .github/workflows/post-merge-deploy-postoffice-mock.yml, .github/workflows/post-merge-deploy-test-harness.yml, .github/workflows/post-merge-deploy-yoti-stub.yml, .github/workflows/pull-request-Dynamo.yml, .github/workflows/pull-request-KMS.yml, .github/workflows/pull-request-gov-notify-stub.yml, .github/workflows/pull-request-ipv-stub.yml, .github/workflows/pull-request-outbound-proxy.yml, .github/workflows/pull-request-postoffice-mock.yml, .github/workflows/pull-request-test-harness.yml, .github/workflows/pull-request-yoti-stub.yml, .github/workflows/pull-request.yml, run-tests.sh
=> Kiwi 1907c Fix API Pipelines

run-tests.sh
Update stub export for pipeline tests
Fix failing Pipeline tests
=> Update stub export for pipeline tests

deploy/template.yaml
Update ExpiredSession lambda to run every 15mins
=> Update ExpiredSession lambda to run every 15mins

deploy/template.yaml, f2f-ipv-stub/src/tests/infrastructure.test.ts, f2f-ipv-stub/template.yaml
Removes dependency between IPV Stub and API stack
=> Remove dependency between IPV Stub and API stack

deploy/template.yaml, f2f-ipv-stub/src/tests/infrastructure.test.ts, f2f-ipv-stub/template.yaml
Reverts govuk-one-login/ipv-cri-f2f-api#516
=> Revert "Remove dependency between IPV Stub and API stack"

.github/workflows/post-merge-deploy-api.yml, .github/workflows/post-merge-deploy-dynamo.yml, .github/workflows/post-merge-deploy-govnotify-stub.yml, .github/workflows/post-merge-deploy-ipv-stub.yml, .github/workflows/post-merge-deploy-kms.yml, .github/workflows/post-merge-deploy-outbound-proxy.yml, .github/workflows/post-merge-deploy-postoffice-mock.yml, .github/workflows/post-merge-deploy-test-harness.yml, .github/workflows/post-merge-deploy-yoti-stub.yml, .github/workflows/pull-request-Dynamo.yml, .github/workflows/pull-request-KMS.yml, .github/workflows/pull-request-gov-notify-stub.yml, .github/workflows/pull-request-ipv-stub.yml, .github/workflows/pull-request-outbound-proxy.yml, .github/workflows/pull-request-postoffice-mock.yml, .github/workflows/pull-request-test-harness.yml, .github/workflows/pull-request-yoti-stub.yml, .github/workflows/pull-request.yml
=> Remove parallel build step

src/package-lock.json, src/package.json, src/tests/infra/template.test.ts
Migrate from AWS CDK v1 to AWS CDK v2
To address vulnerabilities
=> F2F | BE | Migrate from AWS CDK v1 to AWS CDK v2

src/tests/api/ApiTestSteps.ts, src/tests/api/backend/HappyPath.test.ts, src/tests/api/backend/UnhappyPath.test.ts
QA Updates for KIWI-1896 Covering AC'S 1 + 3
AC1 - Successful response when an address is found
AC3 - Unsuccessful response 4XX returned
Testing the changes made as part of KIWI-1896: F2F | BE | Enable Use of Address from Shared Claims in FE
- [KIWI-1896](https://govukverify.atlassian.net/browse/KIWI-1896)
[KIWI-1896]: https://govukverify.atlassian.net/browse/KIWI-1896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Kiwi 1896 qa

deploy/template.yaml
https://govukverify.atlassian.net/browse/IPS-901
Continuation of https://github.com/govuk-one-login/ipv-cri-f2f-api/pull/539
=> IPS-901: fix ExpiredSession Lambda permission reference

gov-notify-stub/gov-notify-spec.yaml
=> Fix GovNotify spec file

src/tests/api/backend/HappyPath.test.ts, src/tests/api/types.ts
Update /session-configuration tests to reflect changes made as part of KIWI-1903
calls to SessionConfiguration endpoint now return pcl_enabled field for all responses
- [KIWI-1903](https://govukverify.atlassian.net/browse/KIWI-1903)
[KIWI-1903]: https://govukverify.atlassian.net/browse/KIWI-1903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1903 QA Updates

src/package.json, src/tests/api/ApiTestSteps.ts, src/tests/api/backend/HappyPath.test.ts
Update tests to make use of /person-info and /person-info-key endpoints to validate postal address
- [KIWI-1937](https://govukverify.atlassian.net/browse/KIWI-1937)
[KIWI-1937]: https://govukverify.atlassian.net/browse/KIWI-1937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Kiwi 1937 QA Updates

yoti-stub/template.yaml
- Fix AWS Transform issue on Yoti stub
- Fix AWS Transform issue on Yoti stub
- Fix AWS Transform issue on Yoti stub
- [IPS-964](https://govukverify.atlassian.net/browse/IPS-964)
[IPS-964]: https://govukverify.atlassian.net/browse/IPS-964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-964: Fix Yoti stub AWS Transform issue

.secrets.baseline, src/jest.setup.ts, src/tests/contract/mocks/kmsClient.ts, src/tests/contract/mocks/sqsClient.ts, src/tests/contract/mocks/ssmClient.ts, src/tests/unit/services/F2fService.test.ts, src/tests/unit/utils/KmsJwtAdapterUtils.test.ts, src/utils/KMSClient.ts, src/utils/KmsJwtAdapter.ts, src/utils/SSMClient.ts, src/utils/SqsClient.ts
Added unit tests to KMS JWT Adapter class
To address lack of test coverage  
- [KIWI-2062](https://govukverify.atlassian.net/browse/KIWI-2062)
[KIWI-2062]: https://govukverify.atlassian.net/browse/KIWI-2062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2062] - F2F | BE | Add unit tests to KMS JWT Adapter class

deploy/template.yaml, src/tests/infra/template.test.ts
- Added LambdaCanaryDeployment preference on updated the pipeline
- Added Code Deploy Service role to allow code deploy
- Set LambdaDeploymentPreference to AllAAatOnce
- Updated lambda functions with the canary deployment configurations
- Added additional alarms for Lambda errors and 5xx errors with lower threshold
- Implement Lambda canary deployments for F2F CRI
- Implement Lambda canary deployments for F2F CRI
- Implement Lambda canary deployments for F2F CRI
- [KIWI-1114](https://govukverify.atlassian.net/browse/KIWI-1114)
[KIWI-1114]: https://govukverify.atlassian.net/browse/KIWI-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-1114: Implement Lambda canary deployments for F2F CRI

src/tests/api/backend/HappyPath.test.ts
Increased test timeout value to align with post PCL values
=> KIWI-1887: Increased expiry test value to align with new values following PCL

deploy/template.yaml
Reverts govuk-one-login/ipv-cri-f2f-api#713
=> Revert "Ips 1407 migrate kiwi and lime wa fs"

.secrets.baseline, src/AddressLocationsHandler.ts, src/GeneratePrintedLetterHandler.ts, src/SendToGovNotifyHandler.ts, src/jest.setup.ts, src/models/EmailResponse.ts, src/services/AddressLocationsProcessor.ts, src/services/DocumentSelectionRequestProcessor.ts, src/services/GeneratePrintedLetterProcessor.ts, src/services/GenerateYotiLetterProcessor.ts, src/services/PdfService.ts, src/services/SendEmailProcessor.ts, src/services/SendEmailService.ts, src/services/SendToGovNotifyProcessor.ts, src/services/SendToGovNotifyService.ts, src/services/ThankYouEmailProcessor.ts, src/services/YotiService.ts, src/services/YotiSessionCompletionProcessor.ts, src/tests/unit/AddressLocationsHandler.test.ts, src/tests/unit/GeneratePrintedLetterHandler.test.ts, src/tests/unit/services/AddressLocationsProcessor.test.ts, src/tests/unit/services/DocumentSelectionRequestProcessor.test.ts, src/tests/unit/services/GeneratePrintedLetterProcessor.test.ts, src/tests/unit/services/GenerateYotiLetterProcessor.test.ts, src/tests/unit/services/PdfService.test.ts, src/tests/unit/services/SendEmailProcessor.test.ts, src/tests/unit/services/SendEmailService.test.ts, src/tests/unit/services/SendToGovNotifyProcessor.test.ts, src/tests/unit/services/SendToGovNotifyService.test.ts, src/tests/unit/services/YotiService.test.ts
with a focus on yoti and PCL. Also addressed some minor bugs found when running the full PCL flow locally
=> KIWI-2130: Added additional metrics to cover the F2F journey

deploy/template.yaml, src/AddressLocationsHandler.ts, src/DocumentSelectionHandler.ts, src/ExpiredSessionsHandler.ts, src/GenerateYotiLetterHandler.ts, src/GovNotifyHandler.ts, src/PersonInfoHandler.ts, src/ReminderEmailHandler.ts, src/SendToGovNotifyHandler.ts, src/SessionConfigHandler.ts, src/SessionHandler.ts, src/ThankYouEmailHandler.ts, src/TriggerYotiCallbackStateMachineHandler.ts, src/UserInfoHandler.ts
Updated feature toggle to enable PCL in prod
Added log lines to ensure redeploy
To turn on PCL in production
=> KIWI-1931: Toggling on PCL in production and adding comments to ensure all lambdas deploy

deploy/template.yaml, src/GeneratePrintedLetterHandler.ts, src/services/EnvironmentVariables.ts
This reverts commit 7a26f8234e77f8e59d1620092f181070c6ae58a3.
=> Revert KIWI-2171

src/tests/api/backend/HappyPath.test.ts
Small fix for API test assertion case
=> [KIWI-XXXX] - Small fix for API test assertion case

deploy/f2f-spec.yaml, src/tests/api/ApiTestSteps.ts, src/tests/api/ApiUtils.ts, src/tests/api/backend/HappyPath.test.ts, src/tests/api/types.ts, src/tests/data/docSelectionPayloadDriversLicenceValidPreferredAddress.json
=> Add timeout before validating F2F_YOTI_PDF_LETTER_POSTED event

deploy/template.yaml, src/tests/api/ApiUtils.ts, src/tests/api/backend/HappyPath.test.ts, test-harness/template.yaml, test-harness/test-harness-spec.yaml
Add automation tests for state machine
Improved coverage around generateYotiLetter and generatePrintedLetter lambdas
- [KIWI-2148](https://govukverify.atlassian.net/browse/KIWI-2148)
[KIWI-2148]: https://govukverify.atlassian.net/browse/KIWI-2148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-2148: F2F | PCL | Add automation tests for state machine

test-harness/template.yaml, test-harness/test-harness-spec.yaml
Removing validation from action until source of validation bug can be identified
=> KIWI-harness removing validation to allow the deployment of the Kiwi test harness

src/tests/api/backend/HappyPath.test.ts, src/tests/data/sharedClaimsPayload2Addresses.json
QA Updates
- [KIWI-2176](https://govukverify.atlassian.net/browse/KIWI-2176)
[KIWI-2176]: https://govukverify.atlassian.net/browse/KIWI-2176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-2176: QA Updates

src/tests/api/backend/HappyPath.test.ts, src/tests/data/sharedClaimsPayload2Addresses.json
=> Kiwi 2176 QA Updates (Up to Date with Main) 

deploy/f2f-spec.yaml
Update to api spec to include additional fields from front-end payload. Also updated field descriptions
=> Update api spec with additional fields in postal_code payload

.secrets.baseline, f2f-ipv-stub/src/events/callbackFailure.json, f2f-ipv-stub/src/events/callbackSuccess.json, f2f-ipv-stub/src/jest.config.ts, f2f-ipv-stub/src/package-lock.json, f2f-ipv-stub/src/package.json, infra-l2-dynamo/src/jest.config.ts, infra-l2-dynamo/src/package-lock.json, infra-l2-dynamo/src/tsconfig.json, infra-l2-kms/src/jest.config.ts, infra-l2-kms/src/package-lock.json, infra-l2-kms/src/package.json, infra-l2-kms/src/tsconfig.json, infra-l2-outbound-proxy/src/jest.config.ts, infra-l2-outbound-proxy/src/package-lock.json, infra-l2-outbound-proxy/src/tsconfig.json
Small additional cleanup for the work already done for [KIWI-2310](https://govukverify.atlassian.net/browse/KIWI-2310) in [this PR](https://github.com/govuk-one-login/ipv-cri-f2f-api/pull/779)
[KIWI-2310]: https://govukverify.atlassian.net/browse/KIWI-2310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2310] - BE | Baseline dependencies and align stub and infra file structures

deploy/f2f-spec.yaml, deploy/template.yaml
Created a copy of the `/.well-known/jwks.json` endpoint for testing purposes and pointed it to the new bucket
To verify contents of the new S3 bucket created using the common infra before pointing the existing JWKS endpoint to it
- [KIWI-2399](https://govukverify.atlassian.net/browse/KIWI-2399)
[KIWI-2399]: https://govukverify.atlassian.net/browse/KIWI-2399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2399] - F2F | Platform | Verify new S3 bucket and connect to existing JWKS endpoint

.github/workflows/post-merge-sonar.yml, .github/workflows/pull-request-sonar.yml
=> updated to reference new sonar-scan version

deploy/template.yaml
Enable key rotation in integration
=> KIWI-2438 - Enable key rotation in integration

deploy/template.yaml
Reverts govuk-one-login/ipv-cri-f2f-api#882
=> Revert "[KIWI-2477] - F2F | Add FMS tags for custom WAF policy migration in lower environments"
